// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class AbilityDBDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/AbilityDB") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static AbilityDBDB _instance = null;
    public static AbilityDBDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(AbilityDBDB)) as AbilityDBDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string num;
		public string name;
		public string info;
		public string type;
		public string AT;
		public string Maxlv;
		public string subtype;
		public string desc;
		public string sprite;
		public string A;
		public string B;
		public string C;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.num = grid[i][1];
			row.name = grid[i][2];
			row.info = grid[i][3];
			row.type = grid[i][4];
			row.AT = grid[i][5];
			row.Maxlv = grid[i][6];
			row.subtype = grid[i][7];
			row.desc = grid[i][8];
			row.sprite = grid[i][9];
			row.A = grid[i][10];
			row.B = grid[i][11];
			row.C = grid[i][12];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_num(string find)
	{
		return rowList.Find(x => x.num == find);
	}
	public List<Row> FindAll_num(string find)
	{
		return rowList.FindAll(x => x.num == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_AT(string find)
	{
		return rowList.Find(x => x.AT == find);
	}
	public List<Row> FindAll_AT(string find)
	{
		return rowList.FindAll(x => x.AT == find);
	}
	public Row Find_Maxlv(string find)
	{
		return rowList.Find(x => x.Maxlv == find);
	}
	public List<Row> FindAll_Maxlv(string find)
	{
		return rowList.FindAll(x => x.Maxlv == find);
	}
	public Row Find_subtype(string find)
	{
		return rowList.Find(x => x.subtype == find);
	}
	public List<Row> FindAll_subtype(string find)
	{
		return rowList.FindAll(x => x.subtype == find);
	}
	public Row Find_desc(string find)
	{
		return rowList.Find(x => x.desc == find);
	}
	public List<Row> FindAll_desc(string find)
	{
		return rowList.FindAll(x => x.desc == find);
	}
	public Row Find_sprite(string find)
	{
		return rowList.Find(x => x.sprite == find);
	}
	public List<Row> FindAll_sprite(string find)
	{
		return rowList.FindAll(x => x.sprite == find);
	}
	public Row Find_A(string find)
	{
		return rowList.Find(x => x.A == find);
	}
	public List<Row> FindAll_A(string find)
	{
		return rowList.FindAll(x => x.A == find);
	}
	public Row Find_B(string find)
	{
		return rowList.Find(x => x.B == find);
	}
	public List<Row> FindAll_B(string find)
	{
		return rowList.FindAll(x => x.B == find);
	}
	public Row Find_C(string find)
	{
		return rowList.Find(x => x.C == find);
	}
	public List<Row> FindAll_C(string find)
	{
		return rowList.FindAll(x => x.C == find);
	}

}