// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class AchievementStatDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/AchievementStat") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static AchievementStatDB _instance = null;
    public static AchievementStatDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(AchievementStatDB)) as AchievementStatDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string level;
		public string EXP;
		public string str;
		public string dex;
		public string intel;
		public string wis;
		public string A;
		public string B;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.level = grid[i][1];
			row.EXP = grid[i][2];
			row.str = grid[i][3];
			row.dex = grid[i][4];
			row.intel = grid[i][5];
			row.wis = grid[i][6];
			row.A = grid[i][7];
			row.B = grid[i][8];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_level(string find)
	{
		return rowList.Find(x => x.level == find);
	}
	public List<Row> FindAll_level(string find)
	{
		return rowList.FindAll(x => x.level == find);
	}
	public Row Find_EXP(string find)
	{
		return rowList.Find(x => x.EXP == find);
	}
	public List<Row> FindAll_EXP(string find)
	{
		return rowList.FindAll(x => x.EXP == find);
	}
	public Row Find_str(string find)
	{
		return rowList.Find(x => x.str == find);
	}
	public List<Row> FindAll_str(string find)
	{
		return rowList.FindAll(x => x.str == find);
	}
	public Row Find_dex(string find)
	{
		return rowList.Find(x => x.dex == find);
	}
	public List<Row> FindAll_dex(string find)
	{
		return rowList.FindAll(x => x.dex == find);
	}
	public Row Find_intel(string find)
	{
		return rowList.Find(x => x.intel == find);
	}
	public List<Row> FindAll_intel(string find)
	{
		return rowList.FindAll(x => x.intel == find);
	}
	public Row Find_wis(string find)
	{
		return rowList.Find(x => x.wis == find);
	}
	public List<Row> FindAll_wis(string find)
	{
		return rowList.FindAll(x => x.wis == find);
	}
	public Row Find_A(string find)
	{
		return rowList.Find(x => x.A == find);
	}
	public List<Row> FindAll_A(string find)
	{
		return rowList.FindAll(x => x.A == find);
	}
	public Row Find_B(string find)
	{
		return rowList.Find(x => x.B == find);
	}
	public List<Row> FindAll_B(string find)
	{
		return rowList.FindAll(x => x.B == find);
	}

}