// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class AchievementDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/Achievement") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static AchievementDB _instance = null;
    public static AchievementDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(AchievementDB)) as AchievementDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string coreid;
		public string name;
		public string description;
		public string type;
		public string subtype;
		public string level;
		public string nextlevel;
		public string count;
		public string item;
		public string itemhowmany;
		public string paneltype;
		public string islast;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.coreid = grid[i][1];
			row.name = grid[i][2];
			row.description = grid[i][3];
			row.type = grid[i][4];
			row.subtype = grid[i][5];
			row.level = grid[i][6];
			row.nextlevel = grid[i][7];
			row.count = grid[i][8];
			row.item = grid[i][9];
			row.itemhowmany = grid[i][10];
			row.paneltype = grid[i][11];
			row.islast = grid[i][12];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_coreid(string find)
	{
		return rowList.Find(x => x.coreid == find);
	}
	public List<Row> FindAll_coreid(string find)
	{
		return rowList.FindAll(x => x.coreid == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_subtype(string find)
	{
		return rowList.Find(x => x.subtype == find);
	}
	public List<Row> FindAll_subtype(string find)
	{
		return rowList.FindAll(x => x.subtype == find);
	}
	public Row Find_level(string find)
	{
		return rowList.Find(x => x.level == find);
	}
	public List<Row> FindAll_level(string find)
	{
		return rowList.FindAll(x => x.level == find);
	}
	public Row Find_nextlevel(string find)
	{
		return rowList.Find(x => x.nextlevel == find);
	}
	public List<Row> FindAll_nextlevel(string find)
	{
		return rowList.FindAll(x => x.nextlevel == find);
	}
	public Row Find_count(string find)
	{
		return rowList.Find(x => x.count == find);
	}
	public List<Row> FindAll_count(string find)
	{
		return rowList.FindAll(x => x.count == find);
	}
	public Row Find_item(string find)
	{
		return rowList.Find(x => x.item == find);
	}
	public List<Row> FindAll_item(string find)
	{
		return rowList.FindAll(x => x.item == find);
	}
	public Row Find_itemhowmany(string find)
	{
		return rowList.Find(x => x.itemhowmany == find);
	}
	public List<Row> FindAll_itemhowmany(string find)
	{
		return rowList.FindAll(x => x.itemhowmany == find);
	}
	public Row Find_paneltype(string find)
	{
		return rowList.Find(x => x.paneltype == find);
	}
	public List<Row> FindAll_paneltype(string find)
	{
		return rowList.FindAll(x => x.paneltype == find);
	}
	public Row Find_islast(string find)
	{
		return rowList.Find(x => x.islast == find);
	}
	public List<Row> FindAll_islast(string find)
	{
		return rowList.FindAll(x => x.islast == find);
	}

}