// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class AntCaveDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/AntCave") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static AntCaveDB _instance = null;
    public static AntCaveDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(AntCaveDB)) as AntCaveDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string rewardid;
		public string count;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.rewardid = grid[i][1];
			row.count = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_rewardid(string find)
	{
		return rowList.Find(x => x.rewardid == find);
	}
	public List<Row> FindAll_rewardid(string find)
	{
		return rowList.FindAll(x => x.rewardid == find);
	}
	public Row Find_count(string find)
	{
		return rowList.Find(x => x.count == find);
	}
	public List<Row> FindAll_count(string find)
	{
		return rowList.FindAll(x => x.count == find);
	}

}