// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class CollectionRenewalDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/CollectionRenewal") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static CollectionRenewalDB _instance = null;
    public static CollectionRenewalDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(CollectionRenewalDB)) as CollectionRenewalDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string num;
		public string isequip;
		public string itemid;
		public string descname;
		public string desc;
		public string hw;
		public string statype;
		public string stat;
		public string statinfo;
		public string type;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.num = grid[i][1];
			row.isequip = grid[i][2];
			row.itemid = grid[i][3];
			row.descname = grid[i][4];
			row.desc = grid[i][5];
			row.hw = grid[i][6];
			row.statype = grid[i][7];
			row.stat = grid[i][8];
			row.statinfo = grid[i][9];
			row.type = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_num(string find)
	{
		return rowList.Find(x => x.num == find);
	}
	public List<Row> FindAll_num(string find)
	{
		return rowList.FindAll(x => x.num == find);
	}
	public Row Find_isequip(string find)
	{
		return rowList.Find(x => x.isequip == find);
	}
	public List<Row> FindAll_isequip(string find)
	{
		return rowList.FindAll(x => x.isequip == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_descname(string find)
	{
		return rowList.Find(x => x.descname == find);
	}
	public List<Row> FindAll_descname(string find)
	{
		return rowList.FindAll(x => x.descname == find);
	}
	public Row Find_desc(string find)
	{
		return rowList.Find(x => x.desc == find);
	}
	public List<Row> FindAll_desc(string find)
	{
		return rowList.FindAll(x => x.desc == find);
	}
	public Row Find_hw(string find)
	{
		return rowList.Find(x => x.hw == find);
	}
	public List<Row> FindAll_hw(string find)
	{
		return rowList.FindAll(x => x.hw == find);
	}
	public Row Find_statype(string find)
	{
		return rowList.Find(x => x.statype == find);
	}
	public List<Row> FindAll_statype(string find)
	{
		return rowList.FindAll(x => x.statype == find);
	}
	public Row Find_stat(string find)
	{
		return rowList.Find(x => x.stat == find);
	}
	public List<Row> FindAll_stat(string find)
	{
		return rowList.FindAll(x => x.stat == find);
	}
	public Row Find_statinfo(string find)
	{
		return rowList.Find(x => x.statinfo == find);
	}
	public List<Row> FindAll_statinfo(string find)
	{
		return rowList.FindAll(x => x.statinfo == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}

}