// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class CollectionDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/Collection") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static CollectionDB _instance = null;
    public static CollectionDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(CollectionDB)) as CollectionDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string setid;
		public string collecttype;
		public string description;
		public string name;
		public string info;
		public string itemid;
		public string howmany;
		public string piecestat;
		public string piecestatvalue;
		public string allpiecestat;
		public string allpiecevalue;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.setid = grid[i][1];
			row.collecttype = grid[i][2];
			row.description = grid[i][3];
			row.name = grid[i][4];
			row.info = grid[i][5];
			row.itemid = grid[i][6];
			row.howmany = grid[i][7];
			row.piecestat = grid[i][8];
			row.piecestatvalue = grid[i][9];
			row.allpiecestat = grid[i][10];
			row.allpiecevalue = grid[i][11];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_setid(string find)
	{
		return rowList.Find(x => x.setid == find);
	}
	public List<Row> FindAll_setid(string find)
	{
		return rowList.FindAll(x => x.setid == find);
	}
	public Row Find_collecttype(string find)
	{
		return rowList.Find(x => x.collecttype == find);
	}
	public List<Row> FindAll_collecttype(string find)
	{
		return rowList.FindAll(x => x.collecttype == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_howmany(string find)
	{
		return rowList.Find(x => x.howmany == find);
	}
	public List<Row> FindAll_howmany(string find)
	{
		return rowList.FindAll(x => x.howmany == find);
	}
	public Row Find_piecestat(string find)
	{
		return rowList.Find(x => x.piecestat == find);
	}
	public List<Row> FindAll_piecestat(string find)
	{
		return rowList.FindAll(x => x.piecestat == find);
	}
	public Row Find_piecestatvalue(string find)
	{
		return rowList.Find(x => x.piecestatvalue == find);
	}
	public List<Row> FindAll_piecestatvalue(string find)
	{
		return rowList.FindAll(x => x.piecestatvalue == find);
	}
	public Row Find_allpiecestat(string find)
	{
		return rowList.Find(x => x.allpiecestat == find);
	}
	public List<Row> FindAll_allpiecestat(string find)
	{
		return rowList.FindAll(x => x.allpiecestat == find);
	}
	public Row Find_allpiecevalue(string find)
	{
		return rowList.Find(x => x.allpiecevalue == find);
	}
	public List<Row> FindAll_allpiecevalue(string find)
	{
		return rowList.FindAll(x => x.allpiecevalue == find);
	}

}