// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class ContentEnterDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/ContentEnter") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static ContentEnterDB _instance = null;
    public static ContentEnterDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(ContentEnterDB)) as ContentEnterDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string num;
		public string needitem;
		public string needhowmany;
		public string mapid;
		public string monid;
		public string reward;
		public string maprank;
		public string uphp;
		public string upattack;
		public string background;
		public string backgroundmobid;
		public string infoname;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.num = grid[i][1];
			row.needitem = grid[i][2];
			row.needhowmany = grid[i][3];
			row.mapid = grid[i][4];
			row.monid = grid[i][5];
			row.reward = grid[i][6];
			row.maprank = grid[i][7];
			row.uphp = grid[i][8];
			row.upattack = grid[i][9];
			row.background = grid[i][10];
			row.backgroundmobid = grid[i][11];
			row.infoname = grid[i][12];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_num(string find)
	{
		return rowList.Find(x => x.num == find);
	}
	public List<Row> FindAll_num(string find)
	{
		return rowList.FindAll(x => x.num == find);
	}
	public Row Find_needitem(string find)
	{
		return rowList.Find(x => x.needitem == find);
	}
	public List<Row> FindAll_needitem(string find)
	{
		return rowList.FindAll(x => x.needitem == find);
	}
	public Row Find_needhowmany(string find)
	{
		return rowList.Find(x => x.needhowmany == find);
	}
	public List<Row> FindAll_needhowmany(string find)
	{
		return rowList.FindAll(x => x.needhowmany == find);
	}
	public Row Find_mapid(string find)
	{
		return rowList.Find(x => x.mapid == find);
	}
	public List<Row> FindAll_mapid(string find)
	{
		return rowList.FindAll(x => x.mapid == find);
	}
	public Row Find_monid(string find)
	{
		return rowList.Find(x => x.monid == find);
	}
	public List<Row> FindAll_monid(string find)
	{
		return rowList.FindAll(x => x.monid == find);
	}
	public Row Find_reward(string find)
	{
		return rowList.Find(x => x.reward == find);
	}
	public List<Row> FindAll_reward(string find)
	{
		return rowList.FindAll(x => x.reward == find);
	}
	public Row Find_maprank(string find)
	{
		return rowList.Find(x => x.maprank == find);
	}
	public List<Row> FindAll_maprank(string find)
	{
		return rowList.FindAll(x => x.maprank == find);
	}
	public Row Find_uphp(string find)
	{
		return rowList.Find(x => x.uphp == find);
	}
	public List<Row> FindAll_uphp(string find)
	{
		return rowList.FindAll(x => x.uphp == find);
	}
	public Row Find_upattack(string find)
	{
		return rowList.Find(x => x.upattack == find);
	}
	public List<Row> FindAll_upattack(string find)
	{
		return rowList.FindAll(x => x.upattack == find);
	}
	public Row Find_background(string find)
	{
		return rowList.Find(x => x.background == find);
	}
	public List<Row> FindAll_background(string find)
	{
		return rowList.FindAll(x => x.background == find);
	}
	public Row Find_backgroundmobid(string find)
	{
		return rowList.Find(x => x.backgroundmobid == find);
	}
	public List<Row> FindAll_backgroundmobid(string find)
	{
		return rowList.FindAll(x => x.backgroundmobid == find);
	}
	public Row Find_infoname(string find)
	{
		return rowList.Find(x => x.infoname == find);
	}
	public List<Row> FindAll_infoname(string find)
	{
		return rowList.FindAll(x => x.infoname == find);
	}

}