// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class EquipChangeDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/EquipChange") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static EquipChangeDB _instance = null;
    public static EquipChangeDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(EquipChangeDB)) as EquipChangeDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string equip;
		public string desc;
		public string itemid;
		public string hw;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.equip = grid[i][1];
			row.desc = grid[i][2];
			row.itemid = grid[i][3];
			row.hw = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_equip(string find)
	{
		return rowList.Find(x => x.equip == find);
	}
	public List<Row> FindAll_equip(string find)
	{
		return rowList.FindAll(x => x.equip == find);
	}
	public Row Find_desc(string find)
	{
		return rowList.Find(x => x.desc == find);
	}
	public List<Row> FindAll_desc(string find)
	{
		return rowList.FindAll(x => x.desc == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_hw(string find)
	{
		return rowList.Find(x => x.hw == find);
	}
	public List<Row> FindAll_hw(string find)
	{
		return rowList.FindAll(x => x.hw == find);
	}

}