// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class EventDropDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/EventDrop") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static EventDropDB _instance = null;
    public static EventDropDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(EventDropDB)) as EventDropDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string itemid;
		public string maptype;
		public string droprate;
		public string mincount;
		public string maxcount;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.itemid = grid[i][0];
			row.maptype = grid[i][1];
			row.droprate = grid[i][2];
			row.mincount = grid[i][3];
			row.maxcount = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_maptype(string find)
	{
		return rowList.Find(x => x.maptype == find);
	}
	public List<Row> FindAll_maptype(string find)
	{
		return rowList.FindAll(x => x.maptype == find);
	}
	public Row Find_droprate(string find)
	{
		return rowList.Find(x => x.droprate == find);
	}
	public List<Row> FindAll_droprate(string find)
	{
		return rowList.FindAll(x => x.droprate == find);
	}
	public Row Find_mincount(string find)
	{
		return rowList.Find(x => x.mincount == find);
	}
	public List<Row> FindAll_mincount(string find)
	{
		return rowList.FindAll(x => x.mincount == find);
	}
	public Row Find_maxcount(string find)
	{
		return rowList.Find(x => x.maxcount == find);
	}
	public List<Row> FindAll_maxcount(string find)
	{
		return rowList.FindAll(x => x.maxcount == find);
	}

}