// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class growthpathDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/growthpath") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static growthpathDB _instance = null;
    public static growthpathDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(growthpathDB)) as growthpathDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string ids;
		public string rank;
		public string equipitems;
		public string dungeonid;
		public string monid;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.ids = grid[i][0];
			row.rank = grid[i][1];
			row.equipitems = grid[i][2];
			row.dungeonid = grid[i][3];
			row.monid = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_ids(string find)
	{
		return rowList.Find(x => x.ids == find);
	}
	public List<Row> FindAll_ids(string find)
	{
		return rowList.FindAll(x => x.ids == find);
	}
	public Row Find_rank(string find)
	{
		return rowList.Find(x => x.rank == find);
	}
	public List<Row> FindAll_rank(string find)
	{
		return rowList.FindAll(x => x.rank == find);
	}
	public Row Find_equipitems(string find)
	{
		return rowList.Find(x => x.equipitems == find);
	}
	public List<Row> FindAll_equipitems(string find)
	{
		return rowList.FindAll(x => x.equipitems == find);
	}
	public Row Find_dungeonid(string find)
	{
		return rowList.Find(x => x.dungeonid == find);
	}
	public List<Row> FindAll_dungeonid(string find)
	{
		return rowList.FindAll(x => x.dungeonid == find);
	}
	public Row Find_monid(string find)
	{
		return rowList.Find(x => x.monid == find);
	}
	public List<Row> FindAll_monid(string find)
	{
		return rowList.FindAll(x => x.monid == find);
	}

}