// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class growthguideDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/growthguide") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static growthguideDB _instance = null;
    public static growthguideDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(growthguideDB)) as growthguideDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string des;
		public string type;
		public string count;
		public string name;
		public string info;
		public string descc;
		public string itemid;
		public string howmany;
		public string exp;
		public string istuto;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.des = grid[i][1];
			row.type = grid[i][2];
			row.count = grid[i][3];
			row.name = grid[i][4];
			row.info = grid[i][5];
			row.descc = grid[i][6];
			row.itemid = grid[i][7];
			row.howmany = grid[i][8];
			row.exp = grid[i][9];
			row.istuto = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_des(string find)
	{
		return rowList.Find(x => x.des == find);
	}
	public List<Row> FindAll_des(string find)
	{
		return rowList.FindAll(x => x.des == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_count(string find)
	{
		return rowList.Find(x => x.count == find);
	}
	public List<Row> FindAll_count(string find)
	{
		return rowList.FindAll(x => x.count == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_descc(string find)
	{
		return rowList.Find(x => x.descc == find);
	}
	public List<Row> FindAll_descc(string find)
	{
		return rowList.FindAll(x => x.descc == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_howmany(string find)
	{
		return rowList.Find(x => x.howmany == find);
	}
	public List<Row> FindAll_howmany(string find)
	{
		return rowList.FindAll(x => x.howmany == find);
	}
	public Row Find_exp(string find)
	{
		return rowList.Find(x => x.exp == find);
	}
	public List<Row> FindAll_exp(string find)
	{
		return rowList.FindAll(x => x.exp == find);
	}
	public Row Find_istuto(string find)
	{
		return rowList.Find(x => x.istuto == find);
	}
	public List<Row> FindAll_istuto(string find)
	{
		return rowList.FindAll(x => x.istuto == find);
	}

}