// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class GuildBuffDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/GuildBuff") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static GuildBuffDB _instance = null;
    public static GuildBuffDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(GuildBuffDB)) as GuildBuffDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string description;
		public string name;
		public string info;
		public string minlv;
		public string maxlv;
		public string upperlv;
		public string ispercent;
		public string sprite;
		public string upgradeGold;
		public string num;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.description = grid[i][1];
			row.name = grid[i][2];
			row.info = grid[i][3];
			row.minlv = grid[i][4];
			row.maxlv = grid[i][5];
			row.upperlv = grid[i][6];
			row.ispercent = grid[i][7];
			row.sprite = grid[i][8];
			row.upgradeGold = grid[i][9];
			row.num = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_minlv(string find)
	{
		return rowList.Find(x => x.minlv == find);
	}
	public List<Row> FindAll_minlv(string find)
	{
		return rowList.FindAll(x => x.minlv == find);
	}
	public Row Find_maxlv(string find)
	{
		return rowList.Find(x => x.maxlv == find);
	}
	public List<Row> FindAll_maxlv(string find)
	{
		return rowList.FindAll(x => x.maxlv == find);
	}
	public Row Find_upperlv(string find)
	{
		return rowList.Find(x => x.upperlv == find);
	}
	public List<Row> FindAll_upperlv(string find)
	{
		return rowList.FindAll(x => x.upperlv == find);
	}
	public Row Find_ispercent(string find)
	{
		return rowList.Find(x => x.ispercent == find);
	}
	public List<Row> FindAll_ispercent(string find)
	{
		return rowList.FindAll(x => x.ispercent == find);
	}
	public Row Find_sprite(string find)
	{
		return rowList.Find(x => x.sprite == find);
	}
	public List<Row> FindAll_sprite(string find)
	{
		return rowList.FindAll(x => x.sprite == find);
	}
	public Row Find_upgradeGold(string find)
	{
		return rowList.Find(x => x.upgradeGold == find);
	}
	public List<Row> FindAll_upgradeGold(string find)
	{
		return rowList.FindAll(x => x.upgradeGold == find);
	}
	public Row Find_num(string find)
	{
		return rowList.Find(x => x.num == find);
	}
	public List<Row> FindAll_num(string find)
	{
		return rowList.FindAll(x => x.num == find);
	}

}