// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class GuildQuestDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/GuildQuest") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static GuildQuestDB _instance = null;
    public static GuildQuestDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(GuildQuestDB)) as GuildQuestDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string name;
		public string info;
		public string description;
		public string rank;
		public string itemid;
		public string howmany;
		public string guildgold;
		public string guildexp;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.name = grid[i][1];
			row.info = grid[i][2];
			row.description = grid[i][3];
			row.rank = grid[i][4];
			row.itemid = grid[i][5];
			row.howmany = grid[i][6];
			row.guildgold = grid[i][7];
			row.guildexp = grid[i][8];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_rank(string find)
	{
		return rowList.Find(x => x.rank == find);
	}
	public List<Row> FindAll_rank(string find)
	{
		return rowList.FindAll(x => x.rank == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_howmany(string find)
	{
		return rowList.Find(x => x.howmany == find);
	}
	public List<Row> FindAll_howmany(string find)
	{
		return rowList.FindAll(x => x.howmany == find);
	}
	public Row Find_guildgold(string find)
	{
		return rowList.Find(x => x.guildgold == find);
	}
	public List<Row> FindAll_guildgold(string find)
	{
		return rowList.FindAll(x => x.guildgold == find);
	}
	public Row Find_guildexp(string find)
	{
		return rowList.Find(x => x.guildexp == find);
	}
	public List<Row> FindAll_guildexp(string find)
	{
		return rowList.FindAll(x => x.guildexp == find);
	}

}