// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class JumpDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/Jump") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static JumpDB _instance = null;
    public static JumpDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(JumpDB)) as JumpDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string name;
		public string equipid;
		public string openclass;
		public string selectclass;
		public string itemid;
		public string itemhw;
		public string equipskill;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.name = grid[i][1];
			row.equipid = grid[i][2];
			row.openclass = grid[i][3];
			row.selectclass = grid[i][4];
			row.itemid = grid[i][5];
			row.itemhw = grid[i][6];
			row.equipskill = grid[i][7];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_equipid(string find)
	{
		return rowList.Find(x => x.equipid == find);
	}
	public List<Row> FindAll_equipid(string find)
	{
		return rowList.FindAll(x => x.equipid == find);
	}
	public Row Find_openclass(string find)
	{
		return rowList.Find(x => x.openclass == find);
	}
	public List<Row> FindAll_openclass(string find)
	{
		return rowList.FindAll(x => x.openclass == find);
	}
	public Row Find_selectclass(string find)
	{
		return rowList.Find(x => x.selectclass == find);
	}
	public List<Row> FindAll_selectclass(string find)
	{
		return rowList.FindAll(x => x.selectclass == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_itemhw(string find)
	{
		return rowList.Find(x => x.itemhw == find);
	}
	public List<Row> FindAll_itemhw(string find)
	{
		return rowList.FindAll(x => x.itemhw == find);
	}
	public Row Find_equipskill(string find)
	{
		return rowList.Find(x => x.equipskill == find);
	}
	public List<Row> FindAll_equipskill(string find)
	{
		return rowList.FindAll(x => x.equipskill == find);
	}

}