// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class LevelDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/Level") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static LevelDB _instance = null;
    public static LevelDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(LevelDB)) as LevelDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string Lv;
		public string RequiredExp;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.Lv = grid[i][0];
			row.RequiredExp = grid[i][1];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_Lv(string find)
	{
		return rowList.Find(x => x.Lv == find);
	}
	public List<Row> FindAll_Lv(string find)
	{
		return rowList.FindAll(x => x.Lv == find);
	}
	public Row Find_RequiredExp(string find)
	{
		return rowList.Find(x => x.RequiredExp == find);
	}
	public List<Row> FindAll_RequiredExp(string find)
	{
		return rowList.FindAll(x => x.RequiredExp == find);
	}

}