// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class MonDropDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/MonDrop") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static MonDropDB _instance = null;
    public static MonDropDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(MonDropDB)) as MonDropDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string description;
		public string Tier;
		public string id;
		public string num;
		public string itemid;
		public string itemnames;
		public string minhowmany;
		public string maxhowmany;
		public string rate;
		public string isshow;
		public string Ispercent;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.description = grid[i][0];
			row.Tier = grid[i][1];
			row.id = grid[i][2];
			row.num = grid[i][3];
			row.itemid = grid[i][4];
			row.itemnames = grid[i][5];
			row.minhowmany = grid[i][6];
			row.maxhowmany = grid[i][7];
			row.rate = grid[i][8];
			row.isshow = grid[i][9];
			row.Ispercent = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_Tier(string find)
	{
		return rowList.Find(x => x.Tier == find);
	}
	public List<Row> FindAll_Tier(string find)
	{
		return rowList.FindAll(x => x.Tier == find);
	}
	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_num(string find)
	{
		return rowList.Find(x => x.num == find);
	}
	public List<Row> FindAll_num(string find)
	{
		return rowList.FindAll(x => x.num == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_itemnames(string find)
	{
		return rowList.Find(x => x.itemnames == find);
	}
	public List<Row> FindAll_itemnames(string find)
	{
		return rowList.FindAll(x => x.itemnames == find);
	}
	public Row Find_minhowmany(string find)
	{
		return rowList.Find(x => x.minhowmany == find);
	}
	public List<Row> FindAll_minhowmany(string find)
	{
		return rowList.FindAll(x => x.minhowmany == find);
	}
	public Row Find_maxhowmany(string find)
	{
		return rowList.Find(x => x.maxhowmany == find);
	}
	public List<Row> FindAll_maxhowmany(string find)
	{
		return rowList.FindAll(x => x.maxhowmany == find);
	}
	public Row Find_rate(string find)
	{
		return rowList.Find(x => x.rate == find);
	}
	public List<Row> FindAll_rate(string find)
	{
		return rowList.FindAll(x => x.rate == find);
	}
	public Row Find_isshow(string find)
	{
		return rowList.Find(x => x.isshow == find);
	}
	public List<Row> FindAll_isshow(string find)
	{
		return rowList.FindAll(x => x.isshow == find);
	}
	public Row Find_Ispercent(string find)
	{
		return rowList.Find(x => x.Ispercent == find);
	}
	public List<Row> FindAll_Ispercent(string find)
	{
		return rowList.FindAll(x => x.Ispercent == find);
	}

}