// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class PassiveDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/Passive") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static PassiveDB _instance = null;
    public static PassiveDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(PassiveDB)) as PassiveDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string description;
		public string name;
		public string info;
		public string type;
		public string subtype;
		public string value;
		public string percent;
		public string A;
		public string B;
		public string C;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.description = grid[i][1];
			row.name = grid[i][2];
			row.info = grid[i][3];
			row.type = grid[i][4];
			row.subtype = grid[i][5];
			row.value = grid[i][6];
			row.percent = grid[i][7];
			row.A = grid[i][8];
			row.B = grid[i][9];
			row.C = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_subtype(string find)
	{
		return rowList.Find(x => x.subtype == find);
	}
	public List<Row> FindAll_subtype(string find)
	{
		return rowList.FindAll(x => x.subtype == find);
	}
	public Row Find_value(string find)
	{
		return rowList.Find(x => x.value == find);
	}
	public List<Row> FindAll_value(string find)
	{
		return rowList.FindAll(x => x.value == find);
	}
	public Row Find_percent(string find)
	{
		return rowList.Find(x => x.percent == find);
	}
	public List<Row> FindAll_percent(string find)
	{
		return rowList.FindAll(x => x.percent == find);
	}
	public Row Find_A(string find)
	{
		return rowList.Find(x => x.A == find);
	}
	public List<Row> FindAll_A(string find)
	{
		return rowList.FindAll(x => x.A == find);
	}
	public Row Find_B(string find)
	{
		return rowList.Find(x => x.B == find);
	}
	public List<Row> FindAll_B(string find)
	{
		return rowList.FindAll(x => x.B == find);
	}
	public Row Find_C(string find)
	{
		return rowList.Find(x => x.C == find);
	}
	public List<Row> FindAll_C(string find)
	{
		return rowList.FindAll(x => x.C == find);
	}

}