// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class smeltpointDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/smeltpoint") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static smeltpointDB _instance = null;
    public static smeltpointDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(smeltpointDB)) as smeltpointDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string level;
		public string smeltcount;
		public string nextsmeltcount;
		public string extradmg;
		public string dmg;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.level = grid[i][0];
			row.smeltcount = grid[i][1];
			row.nextsmeltcount = grid[i][2];
			row.extradmg = grid[i][3];
			row.dmg = grid[i][4];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_level(string find)
	{
		return rowList.Find(x => x.level == find);
	}
	public List<Row> FindAll_level(string find)
	{
		return rowList.FindAll(x => x.level == find);
	}
	public Row Find_smeltcount(string find)
	{
		return rowList.Find(x => x.smeltcount == find);
	}
	public List<Row> FindAll_smeltcount(string find)
	{
		return rowList.FindAll(x => x.smeltcount == find);
	}
	public Row Find_nextsmeltcount(string find)
	{
		return rowList.Find(x => x.nextsmeltcount == find);
	}
	public List<Row> FindAll_nextsmeltcount(string find)
	{
		return rowList.FindAll(x => x.nextsmeltcount == find);
	}
	public Row Find_extradmg(string find)
	{
		return rowList.Find(x => x.extradmg == find);
	}
	public List<Row> FindAll_extradmg(string find)
	{
		return rowList.FindAll(x => x.extradmg == find);
	}
	public Row Find_dmg(string find)
	{
		return rowList.Find(x => x.dmg == find);
	}
	public List<Row> FindAll_dmg(string find)
	{
		return rowList.FindAll(x => x.dmg == find);
	}

}