// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TimeTableDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/TimeTable") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static TimeTableDB _instance = null;
    public static TimeTableDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(TimeTableDB)) as TimeTableDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string enumname;
		public string maxcount;
		public string type;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.enumname = grid[i][0];
			row.maxcount = grid[i][1];
			row.type = grid[i][2];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_enumname(string find)
	{
		return rowList.Find(x => x.enumname == find);
	}
	public List<Row> FindAll_enumname(string find)
	{
		return rowList.FindAll(x => x.enumname == find);
	}
	public Row Find_maxcount(string find)
	{
		return rowList.Find(x => x.maxcount == find);
	}
	public List<Row> FindAll_maxcount(string find)
	{
		return rowList.FindAll(x => x.maxcount == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}

}