// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TradeShopDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/TradeShop") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static TradeShopDB _instance = null;
    public static TradeShopDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(TradeShopDB)) as TradeShopDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string type;
		public string name;
		public string description;
		public string giveid;
		public string givehowmany;
		public string needid;
		public string needhowmany;
		public string buytype;
		public string arrynum;
		public string buyrank;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.type = grid[i][1];
			row.name = grid[i][2];
			row.description = grid[i][3];
			row.giveid = grid[i][4];
			row.givehowmany = grid[i][5];
			row.needid = grid[i][6];
			row.needhowmany = grid[i][7];
			row.buytype = grid[i][8];
			row.arrynum = grid[i][9];
			row.buyrank = grid[i][10];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_name(string find)
	{
		return rowList.Find(x => x.name == find);
	}
	public List<Row> FindAll_name(string find)
	{
		return rowList.FindAll(x => x.name == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_giveid(string find)
	{
		return rowList.Find(x => x.giveid == find);
	}
	public List<Row> FindAll_giveid(string find)
	{
		return rowList.FindAll(x => x.giveid == find);
	}
	public Row Find_givehowmany(string find)
	{
		return rowList.Find(x => x.givehowmany == find);
	}
	public List<Row> FindAll_givehowmany(string find)
	{
		return rowList.FindAll(x => x.givehowmany == find);
	}
	public Row Find_needid(string find)
	{
		return rowList.Find(x => x.needid == find);
	}
	public List<Row> FindAll_needid(string find)
	{
		return rowList.FindAll(x => x.needid == find);
	}
	public Row Find_needhowmany(string find)
	{
		return rowList.Find(x => x.needhowmany == find);
	}
	public List<Row> FindAll_needhowmany(string find)
	{
		return rowList.FindAll(x => x.needhowmany == find);
	}
	public Row Find_buytype(string find)
	{
		return rowList.Find(x => x.buytype == find);
	}
	public List<Row> FindAll_buytype(string find)
	{
		return rowList.FindAll(x => x.buytype == find);
	}
	public Row Find_arrynum(string find)
	{
		return rowList.Find(x => x.arrynum == find);
	}
	public List<Row> FindAll_arrynum(string find)
	{
		return rowList.FindAll(x => x.arrynum == find);
	}
	public Row Find_buyrank(string find)
	{
		return rowList.Find(x => x.buyrank == find);
	}
	public List<Row> FindAll_buyrank(string find)
	{
		return rowList.FindAll(x => x.buyrank == find);
	}

}