// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;

public class TutorialDB : MonoBehaviour
{
    
    public TextAsset ItemDatabase;

   
    public void Awake()
    {
        ItemDatabase = Resources.Load("CSV/Tutorial") as TextAsset;
        Load(ItemDatabase);
    }

    //싱글톤만들기. 변경
    private static TutorialDB _instance = null;
    public static TutorialDB Instance
    {
        get
        {
            if (_instance == null)
            {
                _instance = FindObjectOfType(typeof(TutorialDB)) as TutorialDB;

                if (_instance == null)
                {
                }
            }
            return _instance;
        }
    }


	public class Row
	{
        		public string id;
		public string description;
		public string info;
		public string count;
		public string itemid;
		public string itemhowmany;
		public string type;
		public string typesub;

	}

	List<Row> rowList = new List<Row>();
	bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		for(int i = 1 ; i < grid.Length ; i++)
		{
			Row row = new Row();
			row.id = grid[i][0];
			row.description = grid[i][1];
			row.info = grid[i][2];
			row.count = grid[i][3];
			row.itemid = grid[i][4];
			row.itemhowmany = grid[i][5];
			row.type = grid[i][6];
			row.typesub = grid[i][7];

			rowList.Add(row);
		}
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}

	public Row Find_id(string find)
	{
		return rowList.Find(x => x.id == find);
	}
	public List<Row> FindAll_id(string find)
	{
		return rowList.FindAll(x => x.id == find);
	}
	public Row Find_description(string find)
	{
		return rowList.Find(x => x.description == find);
	}
	public List<Row> FindAll_description(string find)
	{
		return rowList.FindAll(x => x.description == find);
	}
	public Row Find_info(string find)
	{
		return rowList.Find(x => x.info == find);
	}
	public List<Row> FindAll_info(string find)
	{
		return rowList.FindAll(x => x.info == find);
	}
	public Row Find_count(string find)
	{
		return rowList.Find(x => x.count == find);
	}
	public List<Row> FindAll_count(string find)
	{
		return rowList.FindAll(x => x.count == find);
	}
	public Row Find_itemid(string find)
	{
		return rowList.Find(x => x.itemid == find);
	}
	public List<Row> FindAll_itemid(string find)
	{
		return rowList.FindAll(x => x.itemid == find);
	}
	public Row Find_itemhowmany(string find)
	{
		return rowList.Find(x => x.itemhowmany == find);
	}
	public List<Row> FindAll_itemhowmany(string find)
	{
		return rowList.FindAll(x => x.itemhowmany == find);
	}
	public Row Find_type(string find)
	{
		return rowList.Find(x => x.type == find);
	}
	public List<Row> FindAll_type(string find)
	{
		return rowList.FindAll(x => x.type == find);
	}
	public Row Find_typesub(string find)
	{
		return rowList.Find(x => x.typesub == find);
	}
	public List<Row> FindAll_typesub(string find)
	{
		return rowList.FindAll(x => x.typesub == find);
	}

}